import React, { useState } from "react";
import Navbar from "./Navbar"; // Import Navbar
import { useNavigate } from "react-router-dom"; // Import useNavigate for redirection
import "./CuttackPage.css"; // Import the CSS for the Cuttack Page

const CuttackPage = () => {
  const navigate = useNavigate(); // useNavigate hook for redirection

  // List of 50 locations in Cuttack city (same as before)
  const locations = [
    "Nayabazar", "Cuttack Sadar", "Buxi Bazar", "Badambadi", "Jagatpur", 
    "Tulasipur", "Mangalabag", "Link Road", "Choudhury Bazar", "Cantonment Road", 
    "Balia", "Banki", "Barabati", "Kesharpur", "Niali", "Bidanasi", "Kathajodi", 
    "Jobra", "Madhupatna", "Kanheipur", "Sadar Bazar", "Daspalla", "Puri Gate", 
    "Khannagar", "Kalinga Nagar", "Agarpada", "Chhatra Bazar", "Alalabad", 
    "Duhuria", "Bhatapada", "Choudwar", "Brahman Sahi", "Madhupur", "Cuttack City", 
    "Chandanpur", "Ranihat", "Tangi", "Markatnagar", "Chandini Chowk", "Brahamani Bridge", 
    "Banta Sahi", "Sarbathipur", "Sahid Nagar", "Muktapath", "Mahanga", "Patpur", 
    "Badagada", "Dhenkanal", "Alipur", "Raghunathpur", "Banamalipur", "Brahmapur", "Sabar Sahi","Bhubaneswar","Puri", "Dhenkanal"
  ];

   // Distance matrix (you need to fill in the actual distances)
   const distances = {
    "Nayabazar": {
      "Cuttack Sadar": 3,
      "Buxi Bazar": 5,
      "Badambadi": 6,
      "Jagatpur": 8,
      "Tulasipur": 4,
      "Mangalabag": 2,
      "Link Road": 3,
      "Choudhury Bazar": 5,
      "Cantonment Road": 7,
      "Balia": 10,
      "Banki": 12,
      "Barabati": 4,
      "Kesharpur": 3,
      "Niali": 15,
      "Bidanasi": 6,
      "Kathajodi": 7,
      "Jobra": 9,
      "Madhupatna": 5,
      "Kanheipur": 11,
      "Sadar Bazar": 4,
      "Daspalla": 16,
      "Puri Gate": 6,
      "Khannagar": 5,
      "Kalinga Nagar": 7,
      "Agarpada": 18,
      "Chhatra Bazar": 10,
      "Alalabad": 13,
      "Duhuria": 14,
      "Bhatapada": 17,
      "Choudwar": 20,
      "Brahman Sahi": 8,
      "Madhupur": 12,
      "Cuttack City": 5,
      "Chandanpur": 18,
      "Ranihat": 15,
      "Tangi": 22,
      "Markatnagar": 12,
      "Chandini Chowk": 8,
      "Brahamani Bridge": 4,
      "Banta Sahi": 16,
      "Sarbathipur": 17,
      "Sahid Nagar": 11,
      "Muktapath": 13,
      "Mahanga": 19,
      "Patpur": 21,
      "Badagada": 14,
      "Dhenkanal": 30,
      "Alipur": 26,
      "Raghunathpur": 22,
      "Banamalipur": 28,
      "Brahmapur": 35,
      "Sabar Sahi": 9,
      "Bhubaneswar": 27,
      "Puri": 50
    },
    "Cuttack Sadar": {
      "Nayabazar": 3,
      "Buxi Bazar": 2,
      "Badambadi": 1,
      "Jagatpur": 5,
      "Tulasipur": 3,
      "Mangalabag": 3,
      "Link Road": 2,
      "Choudhury Bazar": 4,
      "Cantonment Road": 6,
      "Balia": 9,
      "Banki": 10,
      "Barabati": 2,
      "Kesharpur": 3,
      "Niali": 13,
      "Bidanasi": 5,
      "Kathajodi": 6,
      "Jobra": 8,
      "Madhupatna": 4,
      "Kanheipur": 9,
      "Sadar Bazar": 3,
      "Daspalla": 14,
      "Puri Gate": 5,
      "Khannagar": 4,
      "Kalinga Nagar": 6,
      "Agarpada": 15,
      "Chhatra Bazar": 7,
      "Alalabad": 11,
      "Duhuria": 12,
      "Bhatapada": 14,
      "Choudwar": 18,
      "Brahman Sahi": 6,
      "Madhupur": 10,
      "Cuttack City": 4,
      "Chandanpur": 16,
      "Ranihat": 12,
      "Tangi": 19,
      "Markatnagar": 10,
      "Chandini Chowk": 7,
      "Brahamani Bridge": 3,
      "Banta Sahi": 14,
      "Sarbathipur": 15,
      "Sahid Nagar": 9,
      "Muktapath": 11,
      "Mahanga": 16,
      "Patpur": 18,
      "Badagada": 12,
      "Dhenkanal": 28,
      "Alipur": 24,
      "Raghunathpur": 19,
      "Banamalipur": 25,
      "Brahmapur": 32,
      "Sabar Sahi": 8,
      "Bhubaneswar": 26,
      "Puri": 49
    },

        "Buxi Bazar": {
          "Badambadi": 2,
          "Jagatpur": 4,
          "Tulasipur": 3,
          "Mangalabag": 1,
          "Link Road": 2,
          "Choudhury Bazar": 3,
          "Cantonment Road": 4,
          "Balia": 7,
          "Banki": 9,
          "Barabati": 3,
          "Kesharpur": 2,
          "Niali": 10,
          "Bidanasi": 4,
          "Kathajodi": 5,
          "Jobra": 6,
          "Madhupatna": 3,
          "Kanheipur": 8,
          "Sadar Bazar": 2,
          "Daspalla": 11,
          "Puri Gate": 3,
          "Khannagar": 2,
          "Kalinga Nagar": 4,
          "Agarpada": 12,
          "Chhatra Bazar": 6,
          "Alalabad": 8,
          "Duhuria": 9,
          "Bhatapada": 11,
          "Choudwar": 13,
          "Brahman Sahi": 5,
          "Madhupur": 8,
          "Cuttack City": 3,
          "Chandanpur": 12,
          "Ranihat": 10,
          "Tangi": 15,
          "Markatnagar": 9,
          "Chandini Chowk": 5,
          "Brahamani Bridge": 2,
          "Banta Sahi": 10,
          "Sarbathipur": 11,
          "Sahid Nagar": 7,
          "Muktapath": 8,
          "Mahanga": 13,
          "Patpur": 14,
          "Badagada": 9,
          "Dhenkanal": 25,
          "Alipur": 21,
          "Raghunathpur": 17,
          "Banamalipur": 22,
          "Brahmapur": 30,
          "Sabar Sahi": 6,
          "Bhubaneswar": 22,
          "Puri": 45
        },
        "Badambadi": {
          "Buxi Bazar": 2,
          "Jagatpur": 3,
          "Tulasipur": 2,
          "Mangalabag": 1,
          "Link Road": 2,
          "Choudhury Bazar": 3,
          "Cantonment Road": 3,
          "Balia": 6,
          "Banki": 8,
          "Barabati": 2,
          "Kesharpur": 2,
          "Niali": 9,
          "Bidanasi": 3,
          "Kathajodi": 4,
          "Jobra": 5,
          "Madhupatna": 2,
          "Kanheipur": 7,
          "Sadar Bazar": 1,
          "Daspalla": 10,
          "Puri Gate": 3,
          "Khannagar": 3,
          "Kalinga Nagar": 4,
          "Agarpada": 11,
          "Chhatra Bazar": 5,
          "Alalabad": 7,
          "Duhuria": 8,
          "Bhatapada": 10,
          "Choudwar": 12,
          "Brahman Sahi": 4,
          "Madhupur": 7,
          "Cuttack City": 3,
          "Chandanpur": 11,
          "Ranihat": 9,
          "Tangi": 14,
          "Markatnagar": 8,
          "Chandini Chowk": 4,
          "Brahamani Bridge": 3,
          "Banta Sahi": 9,
          "Sarbathipur": 10,
          "Sahid Nagar": 6,
          "Muktapath": 7,
          "Mahanga": 12,
          "Patpur": 13,
          "Badagada": 8,
          "Dhenkanal": 24,
          "Alipur": 20,
          "Raghunathpur": 16,
          "Banamalipur": 21,
          "Brahmapur": 29,
          "Sabar Sahi": 5,
          "Bhubaneswar": 21,
          "Puri": 44
        },
        "Jagatpur": {
          "Buxi Bazar": 4,
          "Badambadi": 3,
          "Tulasipur": 5,
          "Mangalabag": 4,
          "Link Road": 3,
          "Choudhury Bazar": 5,
          "Cantonment Road": 6,
          "Balia": 8,
          "Banki": 10,
          "Barabati": 4,
          "Kesharpur": 4,
          "Niali": 11,
          "Bidanasi": 6,
          "Kathajodi": 7,
          "Jobra": 8,
          "Madhupatna": 5,
          "Kanheipur": 9,
          "Sadar Bazar": 4,
          "Daspalla": 12,
          "Puri Gate": 5,
          "Khannagar": 4,
          "Kalinga Nagar": 5,
          "Agarpada": 13,
          "Chhatra Bazar": 7,
          "Alalabad": 9,
          "Duhuria": 10,
          "Bhatapada": 12,
          "Choudwar": 14,
          "Brahman Sahi": 6,
          "Madhupur": 9,
          "Cuttack City": 4,
          "Chandanpur": 13,
          "Ranihat": 11,
          "Tangi": 16,
          "Markatnagar": 10,
          "Chandini Chowk": 6,
          "Brahamani Bridge": 3,
          "Banta Sahi": 11,
          "Sarbathipur": 12,
          "Sahid Nagar": 8,
          "Muktapath": 9,
          "Mahanga": 14,
          "Patpur": 15,
          "Badagada": 10,
          "Dhenkanal": 26,
          "Alipur": 22,
          "Raghunathpur": 18,
          "Banamalipur": 23,
          "Brahmapur": 31,
          "Sabar Sahi": 7,
          "Bhubaneswar": 23,
          "Puri": 46
        },
        "Tulasipur": {
    "Mangalabag": 2,
    "Link Road": 3,
    "Badambadi": 2,
    "Buxi Bazar": 3,
    "Jagatpur": 5,
    "Choudhury Bazar": 3,
    "Cantonment Road": 4,
    "Balia": 6,
    "Banki": 8,
    "Barabati": 3,
    "Kesharpur": 3,
    "Niali": 9,
    "Bidanasi": 4,
    "Kathajodi": 5,
    "Jobra": 6,
    "Madhupatna": 3,
    "Kanheipur": 8,
    "Sadar Bazar": 2,
    "Daspalla": 10,
    "Puri Gate": 3,
    "Khannagar": 2,
    "Kalinga Nagar": 4,
    "Agarpada": 12,
    "Chhatra Bazar": 6,
    "Alalabad": 8,
    "Duhuria": 9,
    "Bhatapada": 11,
    "Choudwar": 13,
    "Brahman Sahi": 4,
    "Madhupur": 7,
    "Cuttack City": 3,
    "Chandanpur": 12,
    "Ranihat": 10,
    "Tangi": 15,
    "Markatnagar": 9,
    "Chandini Chowk": 5,
    "Brahamani Bridge": 3,
    "Banta Sahi": 9,
    "Sarbathipur": 10,
    "Sahid Nagar": 6,
    "Muktapath": 7,
    "Mahanga": 12,
    "Patpur": 13,
    "Badagada": 9,
    "Dhenkanal": 24,
    "Alipur": 20,
    "Raghunathpur": 16,
    "Banamalipur": 21,
    "Brahmapur": 29,
    "Sabar Sahi": 6,
    "Bhubaneswar": 21,
    "Puri": 44
  },
  "Mangalabag": {
    "Tulasipur": 2,
    "Link Road": 3,
    "Badambadi": 1,
    "Buxi Bazar": 1,
    "Jagatpur": 4,
    "Choudhury Bazar": 2,
    "Cantonment Road": 3,
    "Balia": 5,
    "Banki": 7,
    "Barabati": 2,
    "Kesharpur": 1,
    "Niali": 8,
    "Bidanasi": 3,
    "Kathajodi": 4,
    "Jobra": 5,
    "Madhupatna": 2,
    "Kanheipur": 7,
    "Sadar Bazar": 1,
    "Daspalla": 9,
    "Puri Gate": 3,
    "Khannagar": 3,
    "Kalinga Nagar": 4,
    "Agarpada": 10,
    "Chhatra Bazar": 4,
    "Alalabad": 6,
    "Duhuria": 7,
    "Bhatapada": 9,
    "Choudwar": 11,
    "Brahman Sahi": 3,
    "Madhupur": 6,
    "Cuttack City": 2,
    "Chandanpur": 10,
    "Ranihat": 8,
    "Tangi": 13,
    "Markatnagar": 7,
    "Chandini Chowk": 3,
    "Brahamani Bridge": 2,
    "Banta Sahi": 8,
    "Sarbathipur": 9,
    "Sahid Nagar": 5,
    "Muktapath": 6,
    "Mahanga": 11,
    "Patpur": 12,
    "Badagada": 8,
    "Dhenkanal": 23,
    "Alipur": 19,
    "Raghunathpur": 15,
    "Banamalipur": 20,
    "Brahmapur": 28,
    "Sabar Sahi": 5,
    "Bhubaneswar": 20,
    "Puri": 43
  },
  "Link Road": {
    "Tulasipur": 3,
    "Mangalabag": 3,
    "Badambadi": 2,
    "Buxi Bazar": 2,
    "Jagatpur": 3,
    "Choudhury Bazar": 4,
    "Cantonment Road": 5,
    "Balia": 7,
    "Banki": 9,
    "Barabati": 3,
    "Kesharpur": 3,
    "Niali": 10,
    "Bidanasi": 4,
    "Kathajodi": 5,
    "Jobra": 6,
    "Madhupatna": 3,
    "Kanheipur": 8,
    "Sadar Bazar": 2,
    "Daspalla": 11,
    "Puri Gate": 4,
    "Khannagar": 3,
    "Kalinga Nagar": 5,
    "Agarpada": 12,
    "Chhatra Bazar": 6,
    "Alalabad": 8,
    "Duhuria": 9,
    "Bhatapada": 11,
    "Choudwar": 13,
    "Brahman Sahi": 5,
    "Madhupur": 8,
    "Cuttack City": 3,
    "Chandanpur": 12,
    "Ranihat": 10,
    "Tangi": 15,
    "Markatnagar": 9,
    "Chandini Chowk": 5,
    "Brahamani Bridge": 3,
    "Banta Sahi": 10,
    "Sarbathipur": 11,
    "Sahid Nagar": 7,
    "Muktapath": 8,
    "Mahanga": 13,
    "Patpur": 14,
    "Badagada": 9,
    "Dhenkanal": 25,
    "Alipur": 21,
    "Raghunathpur": 17,
    "Banamalipur": 22,
    "Brahmapur": 30,
    "Sabar Sahi": 6,
    "Bhubaneswar": 22,
    "Puri": 45
  },

  "Choudhury Bazar": {
    "Cantonment Road": 2,
    "Balia": 5,
    "Banki": 8,
    "Barabati": 2,
    "Tulasipur": 3,
    "Mangalabag": 2,
    "Link Road": 4,
    "Badambadi": 3,
    "Buxi Bazar": 3,
    "Jagatpur": 6,
    "Choudhury Bazar": 0,
    "Kesharpur": 4,
    "Niali": 9,
    "Bidanasi": 6,
    "Kathajodi": 7,
    "Jobra": 8,
    "Madhupatna": 5,
    "Kanheipur": 9,
    "Sadar Bazar": 3,
    "Daspalla": 12,
    "Puri Gate": 4,
    "Khannagar": 3,
    "Kalinga Nagar": 6,
    "Agarpada": 13,
    "Chhatra Bazar": 7,
    "Alalabad": 9,
    "Duhuria": 10,
    "Bhatapada": 12,
    "Choudwar": 14,
    "Brahman Sahi": 5,
    "Madhupur": 9,
    "Cuttack City": 4,
    "Chandanpur": 13,
    "Ranihat": 11,
    "Tangi": 16,
    "Markatnagar": 10,
    "Chandini Chowk": 6,
    "Brahamani Bridge": 4,
    "Banta Sahi": 10,
    "Sarbathipur": 11,
    "Sahid Nagar": 7,
    "Muktapath": 8,
    "Mahanga": 13,
    "Patpur": 14,
    "Badagada": 10,
    "Dhenkanal": 26,
    "Alipur": 22,
    "Raghunathpur": 18,
    "Banamalipur": 23,
    "Brahmapur": 31,
    "Sabar Sahi": 7,
    "Bhubaneswar": 23,
    "Puri": 46
  },
  "Cantonment Road": {
    "Choudhury Bazar": 2,
    "Balia": 4,
    "Banki": 7,
    "Barabati": 3,
    "Tulasipur": 4,
    "Mangalabag": 3,
    "Link Road": 5,
    "Badambadi": 4,
    "Buxi Bazar": 4,
    "Jagatpur": 6,
    "Kesharpur": 3,
    "Niali": 8,
    "Bidanasi": 5,
    "Kathajodi": 6,
    "Jobra": 7,
    "Madhupatna": 4,
    "Kanheipur": 8,
    "Sadar Bazar": 4,
    "Daspalla": 10,
    "Puri Gate": 5,
    "Khannagar": 4,
    "Kalinga Nagar": 5,
    "Agarpada": 11,
    "Chhatra Bazar": 6,
    "Alalabad": 8,
    "Duhuria": 9,
    "Bhatapada": 11,
    "Choudwar": 12,
    "Brahman Sahi": 4,
    "Madhupur": 8,
    "Cuttack City": 3,
    "Chandanpur": 11,
    "Ranihat": 9,
    "Tangi": 14,
    "Markatnagar": 8,
    "Chandini Chowk": 4,
    "Brahamani Bridge": 3,
    "Banta Sahi": 9,
    "Sarbathipur": 10,
    "Sahid Nagar": 6,
    "Muktapath": 7,
    "Mahanga": 12,
    "Patpur": 13,
    "Badagada": 9,
    "Dhenkanal": 24,
    "Alipur": 20,
    "Raghunathpur": 16,
    "Banamalipur": 21,
    "Brahmapur": 29,
    "Sabar Sahi": 6,
    "Bhubaneswar": 21,
    "Puri": 44
  },
  "Balia": {
    "Choudhury Bazar": 5,
    "Cantonment Road": 4,
    "Banki": 5,
    "Barabati": 6,
    "Tulasipur": 6,
    "Mangalabag": 5,
    "Link Road": 7,
    "Badambadi": 6,
    "Buxi Bazar": 7,
    "Jagatpur": 8,
    "Kesharpur": 6,
    "Niali": 11,
    "Bidanasi": 7,
    "Kathajodi": 8,
    "Jobra": 9,
    "Madhupatna": 6,
    "Kanheipur": 10,
    "Sadar Bazar": 5,
    "Daspalla": 13,
    "Puri Gate": 6,
    "Khannagar": 5,
    "Kalinga Nagar": 8,
    "Agarpada": 14,
    "Chhatra Bazar": 8,
    "Alalabad": 10,
    "Duhuria": 11,
    "Bhatapada": 13,
    "Choudwar": 15,
    "Brahman Sahi": 6,
    "Madhupur": 10,
    "Cuttack City": 5,
    "Chandanpur": 14,
    "Ranihat": 12,
    "Tangi": 17,
    "Markatnagar": 11,
    "Chandini Chowk": 7,
    "Brahamani Bridge": 6,
    "Banta Sahi": 11,
    "Sarbathipur": 12,
    "Sahid Nagar": 8,
    "Muktapath": 9,
    "Mahanga": 14,
    "Patpur": 15,
    "Badagada": 11,
    "Dhenkanal": 27,
    "Alipur": 23,
    "Raghunathpur": 19,
    "Banamalipur": 24,
    "Brahmapur": 32,
    "Sabar Sahi": 8,
    "Bhubaneswar": 24,
    "Puri": 47
  },
  "Banki": {
    "Choudhury Bazar": 8,
    "Cantonment Road": 7,
    "Balia": 5,
    "Barabati": 9,
    "Tulasipur": 8,
    "Mangalabag": 7,
    "Link Road": 9,
    "Badambadi": 8,
    "Buxi Bazar": 9,
    "Jagatpur": 10,
    "Kesharpur": 7,
    "Niali": 14,
    "Bidanasi": 10,
    "Kathajodi": 11,
    "Jobra": 12,
    "Madhupatna": 9,
    "Kanheipur": 13,
    "Sadar Bazar": 8,
    "Daspalla": 16,
    "Puri Gate": 9,
    "Khannagar": 8,
    "Kalinga Nagar": 10,
    "Agarpada": 17,
    "Chhatra Bazar": 11,
    "Alalabad": 13,
    "Duhuria": 14,
    "Bhatapada": 16,
    "Choudwar": 18,
    "Brahman Sahi": 9,
    "Madhupur": 13,
    "Cuttack City": 8,
    "Chandanpur": 17,
    "Ranihat": 15,
    "Tangi": 20,
    "Markatnagar": 14,
    "Chandini Chowk": 10,
    "Brahamani Bridge": 9,
    "Banta Sahi": 14,
    "Sarbathipur": 15,
    "Sahid Nagar": 11,
    "Muktapath": 12,
    "Mahanga": 17,
    "Patpur": 18,
    "Badagada": 14,
    "Dhenkanal": 28,
    "Alipur": 24,
    "Raghunathpur": 20,
    "Banamalipur": 25,
    "Brahmapur": 33,
    "Sabar Sahi": 11,
    "Bhubaneswar": 25,
    "Puri": 48
  },
  "Barabati": {
    "Choudhury Bazar": 2,
    "Cantonment Road": 3,
    "Balia": 6,
    "Banki": 9,
    "Tulasipur": 3,
    "Mangalabag": 2,
    "Link Road": 3,
    "Badambadi": 3,
    "Buxi Bazar": 3,
    "Jagatpur": 4,
    "Kesharpur": 3,
    "Niali": 10,
    "Bidanasi": 5,
    "Kathajodi": 6,
    "Jobra": 7,
    "Madhupatna": 4,
    "Kanheipur": 8,
    "Sadar Bazar": 3,
    "Daspalla": 11,
    "Puri Gate": 4,
    "Khannagar": 3,
    "Kalinga Nagar": 5,
    "Agarpada": 12,
    "Chhatra Bazar": 6,
    "Alalabad": 8,
    "Duhuria": 9,
    "Bhatapada": 11,
    "Choudwar": 13,
    "Brahman Sahi": 3,
    "Madhupur": 7,
    "Cuttack City": 3,
    "Chandanpur": 12,
    "Ranihat": 10,
    "Tangi": 15,
    "Markatnagar": 9,
    "Chandini Chowk": 5,
    "Brahamani Bridge": 3,
    "Banta Sahi": 9,
    "Sarbathipur": 10,
    "Sahid Nagar": 6,
    "Muktapath": 7,
    "Mahanga": 12,
    "Patpur": 13,
    "Badagada": 9,
    "Dhenkanal": 24,
    "Alipur": 20,
    "Raghunathpur": 16,
    "Banamalipur": 21,
    "Brahmapur": 29,
    "Sabar Sahi": 6,
    "Bhubaneswar": 21,
    "Puri": 44
  },

  "Kesharpur": {
    "Niali": 12,
    "Bidanasi": 5,
    "Kathajodi": 6,
    "Choudhury Bazar": 4,
    "Cantonment Road": 3,
    "Balia": 6,
    "Banki": 7,
    "Barabati": 3,
    "Tulasipur": 5,
    "Mangalabag": 3,
    "Link Road": 6,
    "Badambadi": 5,
    "Buxi Bazar": 6,
    "Jagatpur": 8,
    "Kesharpur": 0,
    "Jobra": 7,
    "Madhupatna": 4,
    "Kanheipur": 8,
    "Sadar Bazar": 5,
    "Daspalla": 13,
    "Puri Gate": 6,
    "Khannagar": 5,
    "Kalinga Nagar": 8,
    "Agarpada": 14,
    "Chhatra Bazar": 6,
    "Alalabad": 8,
    "Duhuria": 9,
    "Bhatapada": 11,
    "Choudwar": 13,
    "Brahman Sahi": 4,
    "Madhupur": 8,
    "Cuttack City": 5,
    "Chandanpur": 14,
    "Ranihat": 12,
    "Tangi": 17,
    "Markatnagar": 11,
    "Chandini Chowk": 7,
    "Brahamani Bridge": 6,
    "Banta Sahi": 11,
    "Sarbathipur": 12,
    "Sahid Nagar": 8,
    "Muktapath": 9,
    "Mahanga": 14,
    "Patpur": 15,
    "Badagada": 11,
    "Dhenkanal": 27,
    "Alipur": 23,
    "Raghunathpur": 19,
    "Banamalipur": 24,
    "Brahmapur": 32,
    "Sabar Sahi": 8,
    "Bhubaneswar": 24,
    "Puri": 47
  },
  "Niali": {
    "Kesharpur": 12,
    "Bidanasi": 8,
    "Kathajodi": 9,
    "Choudhury Bazar": 9,
    "Cantonment Road": 8,
    "Balia": 11,
    "Banki": 14,
    "Barabati": 10,
    "Tulasipur": 12,
    "Mangalabag": 10,
    "Link Road": 13,
    "Badambadi": 12,
    "Buxi Bazar": 13,
    "Jagatpur": 15,
    "Niali": 0,
    "Jobra": 10,
    "Madhupatna": 9,
    "Kanheipur": 13,
    "Sadar Bazar": 9,
    "Daspalla": 16,
    "Puri Gate": 12,
    "Khannagar": 9,
    "Kalinga Nagar": 12,
    "Agarpada": 19,
    "Chhatra Bazar": 13,
    "Alalabad": 15,
    "Duhuria": 16,
    "Bhatapada": 18,
    "Choudwar": 20,
    "Brahman Sahi": 9,
    "Madhupur": 14,
    "Cuttack City": 9,
    "Chandanpur": 19,
    "Ranihat": 17,
    "Tangi": 22,
    "Markatnagar": 16,
    "Chandini Chowk": 12,
    "Brahamani Bridge": 11,
    "Banta Sahi": 16,
    "Sarbathipur": 17,
    "Sahid Nagar": 13,
    "Muktapath": 14,
    "Mahanga": 19,
    "Patpur": 20,
    "Badagada": 16,
    "Dhenkanal": 29,
    "Alipur": 25,
    "Raghunathpur": 21,
    "Banamalipur": 26,
    "Brahmapur": 34,
    "Sabar Sahi": 13,
    "Bhubaneswar": 28,
    "Puri": 51
  },
  "Bidanasi": {
    "Kesharpur": 5,
    "Niali": 8,
    "Kathajodi": 5,
    "Choudhury Bazar": 6,
    "Cantonment Road": 5,
    "Balia": 7,
    "Banki": 10,
    "Barabati": 5,
    "Tulasipur": 6,
    "Mangalabag": 5,
    "Link Road": 7,
    "Badambadi": 6,
    "Buxi Bazar": 7,
    "Jagatpur": 8,
    "Bidanasi": 0,
    "Jobra": 6,
    "Madhupatna": 5,
    "Kanheipur": 8,
    "Sadar Bazar": 6,
    "Daspalla": 12,
    "Puri Gate": 7,
    "Khannagar": 6,
    "Kalinga Nagar": 9,
    "Agarpada": 14,
    "Chhatra Bazar": 8,
    "Alalabad": 10,
    "Duhuria": 11,
    "Bhatapada": 13,
    "Choudwar": 14,
    "Brahman Sahi": 5,
    "Madhupur": 9,
    "Cuttack City": 5,
    "Chandanpur": 13,
    "Ranihat": 11,
    "Tangi": 16,
    "Markatnagar": 10,
    "Chandini Chowk": 6,
    "Brahamani Bridge": 5,
    "Banta Sahi": 10,
    "Sarbathipur": 11,
    "Sahid Nagar": 7,
    "Muktapath": 8,
    "Mahanga": 13,
    "Patpur": 14,
    "Badagada": 10,
    "Dhenkanal": 24,
    "Alipur": 20,
    "Raghunathpur": 16,
    "Banamalipur": 21,
    "Brahmapur": 29,
    "Sabar Sahi": 7,
    "Bhubaneswar": 22,
    "Puri": 45
  },
  "Kathajodi": {
    "Kesharpur": 6,
    "Niali": 9,
    "Bidanasi": 5,
    "Choudhury Bazar": 7,
    "Cantonment Road": 6,
    "Balia": 8,
    "Banki": 11,
    "Barabati": 6,
    "Tulasipur": 7,
    "Mangalabag": 6,
    "Link Road": 8,
    "Badambadi": 7,
    "Buxi Bazar": 8,
    "Jagatpur": 9,
    "Kathajodi": 0,
    "Jobra": 5,
    "Madhupatna": 6,
    "Kanheipur": 9,
    "Sadar Bazar": 7,
    "Daspalla": 12,
    "Puri Gate": 8,
    "Khannagar": 7,
    "Kalinga Nagar": 10,
    "Agarpada": 14,
    "Chhatra Bazar": 8,
    "Alalabad": 10,
    "Duhuria": 11,
    "Bhatapada": 13,
    "Choudwar": 14,
    "Brahman Sahi": 6,
    "Madhupur": 10,
    "Cuttack City": 6,
    "Chandanpur": 14,
    "Ranihat": 12,
    "Tangi": 17,
    "Markatnagar": 11,
    "Chandini Chowk": 7,
    "Brahamani Bridge": 6,
    "Banta Sahi": 11,
    "Sarbathipur": 12,
    "Sahid Nagar": 8,
    "Muktapath": 9,
    "Mahanga": 14,
    "Patpur": 15,
    "Badagada": 11,
    "Dhenkanal": 25,
    "Alipur": 21,
    "Raghunathpur": 17,
    "Banamalipur": 22,
    "Brahmapur": 30,
    "Sabar Sahi": 8,
    "Bhubaneswar": 23,
    "Puri": 46
  },

  "Jobra": {
    "Madhupatna": 3,
    "Kanheipur": 5,
    "Sadar Bazar": 6,
    "Daspalla": 14,
    "Puri Gate": 9,
    "Kesharpur": 7,
    "Niali": 10,
    "Bidanasi": 6,
    "Kathajodi": 5,
    "Choudhury Bazar": 6,
    "Cantonment Road": 5,
    "Balia": 7,
    "Banki": 9,
    "Barabati": 6,
    "Tulasipur": 7,
    "Mangalabag": 5,
    "Link Road": 6,
    "Badambadi": 7,
    "Buxi Bazar": 8,
    "Jagatpur": 9,
    "Jobra": 0,
    "Khannagar": 8,
    "Kalinga Nagar": 10,
    "Agarpada": 18,
    "Chhatra Bazar": 8,
    "Alalabad": 10,
    "Duhuria": 12,
    "Bhatapada": 14,
    "Choudwar": 16,
    "Brahman Sahi": 6,
    "Madhupur": 11,
    "Cuttack City": 6,
    "Chandanpur": 15,
    "Ranihat": 13,
    "Tangi": 18,
    "Markatnagar": 12,
    "Chandini Chowk": 8,
    "Brahamani Bridge": 7,
    "Banta Sahi": 12,
    "Sarbathipur": 13,
    "Sahid Nagar": 9,
    "Muktapath": 10,
    "Mahanga": 15,
    "Patpur": 16,
    "Badagada": 12,
    "Dhenkanal": 28,
    "Alipur": 24,
    "Raghunathpur": 20,
    "Banamalipur": 25,
    "Brahmapur": 33,
    "Sabar Sahi": 9,
    "Bhubaneswar": 25,
    "Puri": 48
  },
  "Madhupatna": {
    "Jobra": 3,
    "Kanheipur": 4,
    "Sadar Bazar": 5,
    "Daspalla": 12,
    "Puri Gate": 7,
    "Kesharpur": 4,
    "Niali": 9,
    "Bidanasi": 5,
    "Kathajodi": 6,
    "Choudhury Bazar": 5,
    "Cantonment Road": 4,
    "Balia": 6,
    "Banki": 8,
    "Barabati": 5,
    "Tulasipur": 6,
    "Mangalabag": 4,
    "Link Road": 5,
    "Badambadi": 6,
    "Buxi Bazar": 7,
    "Jagatpur": 8,
    "Khannagar": 6,
    "Kalinga Nagar": 8,
    "Agarpada": 16,
    "Chhatra Bazar": 7,
    "Alalabad": 9,
    "Duhuria": 10,
    "Bhatapada": 12,
    "Choudwar": 14,
    "Brahman Sahi": 5,
    "Madhupur": 9,
    "Cuttack City": 5,
    "Chandanpur": 13,
    "Ranihat": 11,
    "Tangi": 16,
    "Markatnagar": 11,
    "Chandini Chowk": 7,
    "Brahamani Bridge": 6,
    "Banta Sahi": 11,
    "Sarbathipur": 12,
    "Sahid Nagar": 8,
    "Muktapath": 9,
    "Mahanga": 14,
    "Patpur": 15,
    "Badagada": 11,
    "Dhenkanal": 23,
    "Alipur": 19,
    "Raghunathpur": 15,
    "Banamalipur": 20,
    "Brahmapur": 28,
    "Sabar Sahi": 8,
    "Bhubaneswar": 21,
    "Puri": 44
  },
  "Kanheipur": {
    "Jobra": 5,
    "Madhupatna": 4,
    "Sadar Bazar": 6,
    "Daspalla": 13,
    "Puri Gate": 8,
    "Kesharpur": 8,
    "Niali": 13,
    "Bidanasi": 8,
    "Kathajodi": 9,
    "Choudhury Bazar": 7,
    "Cantonment Road": 6,
    "Balia": 9,
    "Banki": 11,
    "Barabati": 8,
    "Tulasipur": 9,
    "Mangalabag": 7,
    "Link Road": 8,
    "Badambadi": 9,
    "Buxi Bazar": 10,
    "Jagatpur": 11,
    "Kanheipur": 0,
    "Khannagar": 9,
    "Kalinga Nagar": 11,
    "Agarpada": 17,
    "Chhatra Bazar": 9,
    "Alalabad": 11,
    "Duhuria": 13,
    "Bhatapada": 15,
    "Choudwar": 16,
    "Brahman Sahi": 7,
    "Madhupur": 11,
    "Cuttack City": 6,
    "Chandanpur": 16,
    "Ranihat": 14,
    "Tangi": 19,
    "Markatnagar": 13,
    "Chandini Chowk": 9,
    "Brahamani Bridge": 8,
    "Banta Sahi": 13,
    "Sarbathipur": 14,
    "Sahid Nagar": 10,
    "Muktapath": 11,
    "Mahanga": 16,
    "Patpur": 17,
    "Badagada": 13,
    "Dhenkanal": 26,
    "Alipur": 22,
    "Raghunathpur": 18,
    "Banamalipur": 23,
    "Brahmapur": 31,
    "Sabar Sahi": 10,
    "Bhubaneswar": 24,
    "Puri": 47
  },
  "Sadar Bazar": {
    "Jobra": 6,
    "Madhupatna": 5,
    "Kanheipur": 6,
    "Daspalla": 12,
    "Puri Gate": 7,
    "Kesharpur": 5,
    "Niali": 9,
    "Bidanasi": 6,
    "Kathajodi": 7,
    "Choudhury Bazar": 6,
    "Cantonment Road": 5,
    "Balia": 7,
    "Banki": 9,
    "Barabati": 6,
    "Tulasipur": 7,
    "Mangalabag": 5,
    "Link Road": 6,
    "Badambadi": 7,
    "Buxi Bazar": 8,
    "Jagatpur": 9,
    "Khannagar": 6,
    "Kalinga Nagar": 9,
    "Agarpada": 16,
    "Chhatra Bazar": 7,
    "Alalabad": 9,
    "Duhuria": 10,
    "Bhatapada": 12,
    "Choudwar": 13,
    "Brahman Sahi": 6,
    "Madhupur": 9,
    "Cuttack City": 6,
    "Chandanpur": 14,
    "Ranihat": 12,
    "Tangi": 17,
    "Markatnagar": 11,
    "Chandini Chowk": 7,
    "Brahamani Bridge": 6,
    "Banta Sahi": 11,
    "Sarbathipur": 12,
    "Sahid Nagar": 8,
    "Muktapath": 9,
    "Mahanga": 14,
    "Patpur": 15,
    "Badagada": 11,
    "Dhenkanal": 24,
    "Alipur": 20,
    "Raghunathpur": 16,
    "Banamalipur": 21,
    "Brahmapur": 29,
    "Sabar Sahi": 7,
    "Bhubaneswar": 22,
    "Puri": 45
  },

  "Khannagar": {
    "Kalinga Nagar": 5,
    "Agarpada": 12,
    "Chhatra Bazar": 8,
    "Alalabad": 10,
    "Jobra": 8,
    "Madhupatna": 6,
    "Kanheipur": 9,
    "Sadar Bazar": 6,
    "Daspalla": 18,
    "Puri Gate": 10,
    "Kesharpur": 7,
    "Niali": 11,
    "Bidanasi": 7,
    "Kathajodi": 6,
    "Choudhury Bazar": 6,
    "Cantonment Road": 5,
    "Balia": 7,
    "Banki": 10,
    "Barabati": 7,
    "Tulasipur": 8,
    "Mangalabag": 6,
    "Link Road": 7,
    "Badambadi": 8,
    "Buxi Bazar": 9,
    "Jagatpur": 10,
    "Khannagar": 0,
    "Dhenkanal": 30,
    "Alipur": 26,
    "Raghunathpur": 22,
    "Banamalipur": 27,
    "Brahmapur": 35,
    "Sabar Sahi": 10,
    "Bhubaneswar": 20,
    "Puri": 48
  },
  "Kalinga Nagar": {
    "Khannagar": 5,
    "Agarpada": 11,
    "Chhatra Bazar": 7,
    "Alalabad": 9,
    "Jobra": 9,
    "Madhupatna": 8,
    "Kanheipur": 10,
    "Sadar Bazar": 9,
    "Daspalla": 17,
    "Puri Gate": 11,
    "Kesharpur": 8,
    "Niali": 12,
    "Bidanasi": 8,
    "Kathajodi": 7,
    "Choudhury Bazar": 7,
    "Cantonment Road": 6,
    "Balia": 9,
    "Banki": 12,
    "Barabati": 8,
    "Tulasipur": 9,
    "Mangalabag": 7,
    "Link Road": 8,
    "Badambadi": 9,
    "Buxi Bazar": 10,
    "Jagatpur": 11,
    "Dhenkanal": 24,
    "Alipur": 20,
    "Raghunathpur": 16,
    "Banamalipur": 21,
    "Brahmapur": 29,
    "Sabar Sahi": 9,
    "Bhubaneswar": 23,
    "Puri": 46
  },
  "Agarpada": {
    "Khannagar": 12,
    "Kalinga Nagar": 12,
    "Chhatra Bazar": 15,
    "Alalabad": 17,
    "Jobra": 18,
    "Madhupatna": 16,
    "Kanheipur": 19,
    "Sadar Bazar": 16,
    "Daspalla": 25,
    "Puri Gate": 17,
    "Kesharpur": 18,
    "Niali": 22,
    "Bidanasi": 18,
    "Kathajodi": 17,
    "Choudhury Bazar": 16,
    "Cantonment Road": 15,
    "Balia": 19,
    "Banki": 22,
    "Barabati": 18,
    "Tulasipur": 19,
    "Mangalabag": 17,
    "Link Road": 18,
    "Badambadi": 19,
    "Buxi Bazar": 20,
    "Jagatpur": 21,
    "Dhenkanal": 35,
    "Alipur": 31,
    "Raghunathpur": 27,
    "Banamalipur": 32,
    "Brahmapur": 40,
    "Sabar Sahi": 17,
    "Bhubaneswar": 33,
    "Puri": 55
  },
  "Chhatra Bazar": {
    "Khannagar": 8,
    "Kalinga Nagar": 7,
    "Agarpada": 15,
    "Alalabad": 12,
    "Jobra": 8,
    "Madhupatna": 7,
    "Kanheipur": 10,
    "Sadar Bazar": 7,
    "Daspalla": 16,
    "Puri Gate": 9,
    "Kesharpur": 9,
    "Niali": 14,
    "Bidanasi": 9,
    "Kathajodi": 8,
    "Choudhury Bazar": 7,
    "Cantonment Road": 6,
    "Balia": 9,
    "Banki": 11,
    "Barabati": 9,
    "Tulasipur": 10,
    "Mangalabag": 8,
    "Link Road": 9,
    "Badambadi": 10,
    "Buxi Bazar": 11,
    "Jagatpur": 12,
    "Dhenkanal": 25,
    "Alipur": 21,
    "Raghunathpur": 17,
    "Banamalipur": 22,
    "Brahmapur": 30,
    "Sabar Sahi": 10,
    "Bhubaneswar": 19,
    "Puri": 43
  },
  "Alalabad": {
    "Khannagar": 10,
    "Kalinga Nagar": 9,
    "Agarpada": 17,
    "Chhatra Bazar": 6,
    "Jobra": 10,
    "Madhupatna": 9,
    "Kanheipur": 12,
    "Sadar Bazar": 9,
    "Daspalla": 19,
    "Puri Gate": 12,
    "Kesharpur": 10,
    "Niali": 15,
    "Bidanasi": 10,
    "Kathajodi": 9,
    "Choudhury Bazar": 9,
    "Cantonment Road": 8,
    "Balia": 12,
    "Banki": 15,
    "Barabati": 10,
    "Tulasipur": 12,
    "Mangalabag": 9,
    "Link Road": 10,
    "Badambadi": 12,
    "Buxi Bazar": 13,
    "Jagatpur": 14,
    "Alalabad": 0,
    "Dhenkanal": 28,
    "Alipur": 24,
    "Raghunathpur": 20,
    "Banamalipur": 25,
    "Brahmapur": 33,
    "Sabar Sahi": 12,
    "Bhubaneswar": 22,
    "Puri": 47
  },

    "Duhuria": {
      "Bhatapada": 10,
      "Choudwar": 15,
      "Brahman Sahi": 12,
      "Madhupur": 14,
      "Cuttack City": 8,
      "Jobra": 7,
      "Madhupatna": 9,
      "Kanheipur": 12,
      "Sadar Bazar": 10,
      "Daspalla": 18,
      "Puri Gate": 9,
      "Kesharpur": 8,
      "Niali": 13,
      "Bidanasi": 9,
      "Kathajodi": 8,
      "Choudhury Bazar": 7,
      "Cantonment Road": 8,
      "Balia": 10,
      "Banki": 14,
      "Barabati": 9,
      "Tulasipur": 10,
      "Mangalabag": 8,
      "Link Road": 9,
      "Badambadi": 10,
      "Buxi Bazar": 11,
      "Jagatpur": 12,
      "Dhenkanal": 28,
      "Alipur": 24,
      "Raghunathpur": 20,
      "Banamalipur": 25,
      "Brahmapur": 33,
      "Sabar Sahi": 10,
      "Bhubaneswar": 21,
      "Puri": 45
    },
    "Bhatapada": {
      "Duhuria": 10,
      "Choudwar": 11,
      "Brahman Sahi": 8,
      "Madhupur": 10,
      "Cuttack City": 7,
      "Jobra": 6,
      "Madhupatna": 7,
      "Kanheipur": 9,
      "Sadar Bazar": 7,
      "Daspalla": 16,
      "Puri Gate": 8,
      "Kesharpur": 6,
      "Niali": 11,
      "Bidanasi": 7,
      "Kathajodi": 6,
      "Choudhury Bazar": 6,
      "Cantonment Road": 5,
      "Balia": 8,
      "Banki": 12,
      "Barabati": 7,
      "Tulasipur": 8,
      "Mangalabag": 7,
      "Link Road": 8,
      "Badambadi": 9,
      "Buxi Bazar": 9,
      "Jagatpur": 10,
      "Dhenkanal": 27,
      "Alipur": 23,
      "Raghunathpur": 19,
      "Banamalipur": 24,
      "Brahmapur": 32,
      "Sabar Sahi": 9,
      "Bhubaneswar": 22,
      "Puri": 44
    },
    "Choudwar": {
      "Duhuria": 15,
      "Bhatapada": 11,
      "Brahman Sahi": 16,
      "Madhupur": 17,
      "Cuttack City": 11,
      "Jobra": 10,
      "Madhupatna": 12,
      "Kanheipur": 14,
      "Sadar Bazar": 12,
      "Daspalla": 22,
      "Puri Gate": 13,
      "Kesharpur": 11,
      "Niali": 17,
      "Bidanasi": 12,
      "Kathajodi": 11,
      "Choudhury Bazar": 12,
      "Cantonment Road": 11,
      "Balia": 14,
      "Banki": 18,
      "Barabati": 13,
      "Tulasipur": 14,
      "Mangalabag": 13,
      "Link Road": 14,
      "Badambadi": 14,
      "Buxi Bazar": 15,
      "Jagatpur": 16,
      "Dhenkanal": 25,
      "Alipur": 21,
      "Raghunathpur": 17,
      "Banamalipur": 22,
      "Brahmapur": 30,
      "Sabar Sahi": 13,
      "Bhubaneswar": 26,
      "Puri": 48
    },
    "Brahman Sahi": {
      "Duhuria": 12,
      "Bhatapada": 8,
      "Choudwar": 16,
      "Madhupur": 11,
      "Cuttack City": 6,
      "Jobra": 6,
      "Madhupatna": 7,
      "Kanheipur": 9,
      "Sadar Bazar": 7,
      "Daspalla": 14,
      "Puri Gate": 9,
      "Kesharpur": 7,
      "Niali": 12,
      "Bidanasi": 8,
      "Kathajodi": 7,
      "Choudhury Bazar": 7,
      "Cantonment Road": 6,
      "Balia": 9,
      "Banki": 13,
      "Barabati": 8,
      "Tulasipur": 9,
      "Mangalabag": 7,
      "Link Road": 8,
      "Badambadi": 9,
      "Buxi Bazar": 10,
      "Jagatpur": 11,
      "Dhenkanal": 22,
      "Alipur": 18,
      "Raghunathpur": 14,
      "Banamalipur": 19,
      "Brahmapur": 27,
      "Sabar Sahi": 8,
      "Bhubaneswar": 21,
      "Puri": 42
    },
    "Madhupur": {
      "Duhuria": 14,
      "Bhatapada": 10,
      "Choudwar": 17,
      "Brahman Sahi": 11,
      "Cuttack City": 9,
      "Jobra": 8,
      "Madhupatna": 10,
      "Kanheipur": 13,
      "Sadar Bazar": 11,
      "Daspalla": 19,
      "Puri Gate": 10,
      "Kesharpur": 9,
      "Niali": 14,
      "Bidanasi": 10,
      "Kathajodi": 9,
      "Choudhury Bazar": 10,
      "Cantonment Road": 9,
      "Balia": 12,
      "Banki": 16,
      "Barabati": 10,
      "Tulasipur": 11,
      "Mangalabag": 9,
      "Link Road": 10,
      "Badambadi": 11,
      "Buxi Bazar": 12,
      "Jagatpur": 13,
      "Dhenkanal": 21,
      "Alipur": 17,
      "Raghunathpur": 13,
      "Banamalipur": 18,
      "Brahmapur": 26,
      "Sabar Sahi": 11,
      "Bhubaneswar": 20,
      "Puri": 40
    },
    "Cuttack City": {
      "Duhuria": 8,
      "Bhatapada": 7,
      "Choudwar": 11,
      "Brahman Sahi": 6,
      "Madhupur": 9,
      "Jobra": 5,
      "Madhupatna": 6,
      "Kanheipur": 8,
      "Sadar Bazar": 6,
      "Daspalla": 15,
      "Puri Gate": 8,
      "Kesharpur": 7,
      "Niali": 11,
      "Bidanasi": 7,
      "Kathajodi": 6,
      "Choudhury Bazar": 6,
      "Cantonment Road": 5,
      "Balia": 8,
      "Banki": 11,
      "Barabati": 7,
      "Tulasipur": 8,
      "Mangalabag": 6,
      "Link Road": 7,
      "Badambadi": 8,
      "Buxi Bazar": 9,
      "Jagatpur": 10,
      "Dhenkanal": 23,
      "Alipur": 19,
      "Raghunathpur": 15,
      "Banamalipur": 20,
      "Brahmapur": 28,
      "Sabar Sahi": 8,
      "Bhubaneswar": 19,
      "Puri": 41
    },

    "Chandanpur": {
        "Ranihat": 12,
        "Tangi": 14,
        "Markatnagar": 10,
        "Chandini Chowk": 9,
        "Brahman Bridge": 13,
        "Duhuria": 22,
        "Bhatapada": 18,
        "Choudwar": 20,
        "Brahman Sahi": 17,
        "Madhupur": 16,
        "Cuttack City": 18,
        "Jobra": 20,
        "Madhupatna": 15,
        "Kanheipur": 13,
        "Sadar Bazar": 16,
        "Daspalla": 28,
        "Puri Gate": 19,
        "Kesharpur": 15,
        "Niali": 22,
        "Bidanasi": 18,
        "Kathajodi": 14,
        "Choudhury Bazar": 18,
        "Cantonment Road": 16,
        "Balia": 12,
        "Banki": 20,
        "Barabati": 14,
        "Tulasipur": 20,
        "Mangalabag": 17,
        "Link Road": 15,
        "Badambadi": 18,
        "Buxi Bazar": 19,
        "Jagatpur": 22,
        "Dhenkanal": 36,
        "Alipur": 31,
        "Raghunathpur": 28,
        "Banamalipur": 35,
        "Brahmapur": 40,
        "Sabar Sahi": 18,
        "Bhubaneswar": 25,
        "Puri": 48
      },
      "Ranihat": {
        "Chandanpur": 12,
        "Tangi": 9,
        "Markatnagar": 7,
        "Chandini Chowk": 8,
        "Brahman Bridge": 12,
        "Duhuria": 25,
        "Bhatapada": 20,
        "Choudwar": 22,
        "Brahman Sahi": 18,
        "Madhupur": 17,
        "Cuttack City": 18,
        "Jobra": 20,
        "Madhupatna": 16,
        "Kanheipur": 15,
        "Sadar Bazar": 18,
        "Daspalla": 32,
        "Puri Gate": 22,
        "Kesharpur": 18,
        "Niali": 24,
        "Bidanasi": 20,
        "Kathajodi": 16,
        "Choudhury Bazar": 20,
        "Cantonment Road": 19,
        "Balia": 15,
        "Banki": 19,
        "Barabati": 17,
        "Tulasipur": 19,
        "Mangalabag": 18,
        "Link Road": 17,
        "Badambadi": 21,
        "Buxi Bazar": 22,
        "Jagatpur": 23,
        "Dhenkanal": 34,
        "Alipur": 29,
        "Raghunathpur": 25,
        "Banamalipur": 30,
        "Brahmapur": 38,
        "Sabar Sahi": 22,
        "Bhubaneswar": 28,
        "Puri": 50
      },
      "Tangi": {
        "Chandanpur": 14,
        "Ranihat": 9,
        "Markatnagar": 10,
        "Chandini Chowk": 12,
        "Brahman Bridge": 16,
        "Duhuria": 27,
        "Bhatapada": 22,
        "Choudwar": 23,
        "Brahman Sahi": 20,
        "Madhupur": 19,
        "Cuttack City": 20,
        "Jobra": 23,
        "Madhupatna": 18,
        "Kanheipur": 17,
        "Sadar Bazar": 19,
        "Daspalla": 33,
        "Puri Gate": 24,
        "Kesharpur": 19,
        "Niali": 26,
        "Bidanasi": 22,
        "Kathajodi": 17,
        "Choudhury Bazar": 22,
        "Cantonment Road": 20,
        "Balia": 16,
        "Banki": 23,
        "Barabati": 18,
        "Tulasipur": 21,
        "Mangalabag": 19,
        "Link Road": 18,
        "Badambadi": 21,
        "Buxi Bazar": 22,
        "Jagatpur": 24,
        "Dhenkanal": 35,
        "Alipur": 31,
        "Raghunathpur": 27,
        "Banamalipur": 33,
        "Brahmapur": 41,
        "Sabar Sahi": 23,
        "Bhubaneswar": 30,
        "Puri": 52
      },
      "Markatnagar": {
        "Chandanpur": 10,
        "Ranihat": 7,
        "Tangi": 10,
        "Chandini Chowk": 9,
        "Brahman Bridge": 13,
        "Duhuria": 21,
        "Bhatapada": 17,
        "Choudwar": 19,
        "Brahman Sahi": 16,
        "Madhupur": 15,
        "Cuttack City": 17,
        "Jobra": 19,
        "Madhupatna": 14,
        "Kanheipur": 13,
        "Sadar Bazar": 16,
        "Daspalla": 29,
        "Puri Gate": 20,
        "Kesharpur": 15,
        "Niali": 21,
        "Bidanasi": 17,
        "Kathajodi": 13,
        "Choudhury Bazar": 17,
        "Cantonment Road": 15,
        "Balia": 12,
        "Banki": 18,
        "Barabati": 14,
        "Tulasipur": 19,
        "Mangalabag": 16,
        "Link Road": 15,
        "Badambadi": 19,
        "Buxi Bazar": 20,
        "Jagatpur": 21,
        "Dhenkanal": 32,
        "Alipur": 28,
        "Raghunathpur": 24,
        "Banamalipur": 30,
        "Brahmapur": 38,
        "Sabar Sahi": 18,
        "Bhubaneswar": 27,
        "Puri": 49
      },
      "Chandini Chowk": {
        "Chandanpur": 9,
        "Ranihat": 8,
        "Tangi": 12,
        "Markatnagar": 9,
        "Brahman Bridge": 14,
        "Duhuria": 20,
        "Bhatapada": 18,
        "Choudwar": 19,
        "Brahman Sahi": 17,
        "Madhupur": 16,
        "Cuttack City": 17,
        "Jobra": 18,
        "Madhupatna": 13,
        "Kanheipur": 14,
        "Sadar Bazar": 16,
        "Daspalla": 28,
        "Puri Gate": 19,
        "Kesharpur": 16,
        "Niali": 22,
        "Bidanasi": 17,
        "Kathajodi": 14,
        "Choudhury Bazar": 17,
        "Cantonment Road": 15,
        "Balia": 13,
        "Banki": 21,
        "Barabati": 16,
        "Tulasipur": 18,
        "Mangalabag": 15,
        "Link Road": 14,
        "Badambadi": 18,
        "Buxi Bazar": 19,
        "Jagatpur": 21,
        "Dhenkanal": 33,
        "Alipur": 29,
        "Raghunathpur": 26,
        "Banamalipur": 32,
        "Brahmapur": 39,
        "Sabar Sahi": 17,
        "Bhubaneswar": 26,
        "Puri": 48
      },
      "Brahman Bridge": {
        "Chandanpur": 13,
        "Ranihat": 12,
        "Tangi": 16,
        "Markatnagar": 13,
        "Chandini Chowk": 14,
        "Duhuria": 25,
        "Bhatapada": 21,
        "Choudwar": 23,
        "Brahman Sahi": 19,
        "Madhupur": 18,
        "Cuttack City": 19,
        "Jobra": 21,
        "Madhupatna": 16,
        "Kanheipur": 15,
        "Sadar Bazar": 18,
        "Daspalla": 30,
        "Puri Gate": 21,
        "Kesharpur": 18,
        "Niali": 24,
        "Bidanasi": 21,
        "Kathajodi": 17,
        "Choudhury Bazar": 21,
        "Cantonment Road": 18,
        "Balia": 17,
        "Banki": 23,
        "Barabati": 18,
        "Tulasipur": 21,
        "Mangalabag": 19,
        "Link Road": 18,
        "Badambadi": 22,
        "Buxi Bazar": 23,
        "Jagatpur": 24,
        "Dhenkanal": 35,
        "Alipur": 31,
        "Raghunathpur": 28,
        "Banamalipur": 34,
        "Brahmapur": 42,
        "Sabar Sahi": 21,
        "Bhubaneswar": 29,
        "Puri": 51
      },

      "Banta Sahi": {
    "Sarbathipur": 6,
    "Sahid Nagar": 8,
    "Muktapath": 12,
    "Mahanga": 24,
    "Patpur": 22,
    "Duhuria": 28,
    "Bhatapada": 25,
    "Choudwar": 22,
    "Brahman Sahi": 18,
    "Madhupur": 21,
    "Cuttack City": 19,
    "Jobra": 24,
    "Madhupatna": 18,
    "Kanheipur": 17,
    "Sadar Bazar": 19,
    "Daspalla": 35,
    "Puri Gate": 26,
    "Kesharpur": 22,
    "Niali": 31,
    "Bidanasi": 28,
    "Kathajodi": 19,
    "Choudhury Bazar": 21,
    "Cantonment Road": 19,
    "Balia": 15,
    "Banki": 20,
    "Barabati": 19,
    "Tulasipur": 22,
    "Mangalabag": 21,
    "Link Road": 20,
    "Badambadi": 22,
    "Buxi Bazar": 23,
    "Jagatpur": 25,
    "Dhenkanal": 40,
    "Alipur": 34,
    "Raghunathpur": 30,
    "Banamalipur": 38,
    "Brahmapur": 45,
    "Sabar Sahi": 23,
    "Bhubaneswar": 32,
    "Puri": 55
  },
  "Sarbathipur": {
    "Banta Sahi": 6,
    "Sahid Nagar": 10,
    "Muktapath": 13,
    "Mahanga": 25,
    "Patpur": 23,
    "Duhuria": 29,
    "Bhatapada": 26,
    "Choudwar": 23,
    "Brahman Sahi": 19,
    "Madhupur": 22,
    "Cuttack City": 20,
    "Jobra": 25,
    "Madhupatna": 19,
    "Kanheipur": 18,
    "Sadar Bazar": 20,
    "Daspalla": 36,
    "Puri Gate": 27,
    "Kesharpur": 23,
    "Niali": 32,
    "Bidanasi": 29,
    "Kathajodi": 20,
    "Choudhury Bazar": 22,
    "Cantonment Road": 20,
    "Balia": 16,
    "Banki": 21,
    "Barabati": 20,
    "Tulasipur": 23,
    "Mangalabag": 22,
    "Link Road": 21,
    "Badambadi": 23,
    "Buxi Bazar": 24,
    "Jagatpur": 26,
    "Dhenkanal": 41,
    "Alipur": 35,
    "Raghunathpur": 31,
    "Banamalipur": 39,
    "Brahmapur": 46,
    "Sabar Sahi": 24,
    "Bhubaneswar": 33,
    "Puri": 56
  },
  "Sahid Nagar": {
    "Banta Sahi": 8,
    "Sarbathipur": 10,
    "Muktapath": 14,
    "Mahanga": 26,
    "Patpur": 24,
    "Duhuria": 30,
    "Bhatapada": 27,
    "Choudwar": 24,
    "Brahman Sahi": 20,
    "Madhupur": 23,
    "Cuttack City": 21,
    "Jobra": 26,
    "Madhupatna": 20,
    "Kanheipur": 19,
    "Sadar Bazar": 21,
    "Daspalla": 37,
    "Puri Gate": 28,
    "Kesharpur": 24,
    "Niali": 33,
    "Bidanasi": 30,
    "Kathajodi": 21,
    "Choudhury Bazar": 23,
    "Cantonment Road": 21,
    "Balia": 17,
    "Banki": 22,
    "Barabati": 21,
    "Tulasipur": 24,
    "Mangalabag": 23,
    "Link Road": 22,
    "Badambadi": 24,
    "Buxi Bazar": 25,
    "Jagatpur": 27,
    "Dhenkanal": 42,
    "Alipur": 36,
    "Raghunathpur": 32,
    "Banamalipur": 40,
    "Brahmapur": 47,
    "Sabar Sahi": 25,
    "Bhubaneswar": 34,
    "Puri": 57
  },
  "Muktapath": {
    "Banta Sahi": 12,
    "Sarbathipur": 13,
    "Sahid Nagar": 14,
    "Mahanga": 27,
    "Patpur": 25,
    "Duhuria": 31,
    "Bhatapada": 28,
    "Choudwar": 25,
    "Brahman Sahi": 21,
    "Madhupur": 24,
    "Cuttack City": 22,
    "Jobra": 27,
    "Madhupatna": 21,
    "Kanheipur": 20,
    "Sadar Bazar": 22,
    "Daspalla": 38,
    "Puri Gate": 29,
    "Kesharpur": 25,
    "Niali": 34,
    "Bidanasi": 31,
    "Kathajodi": 22,
    "Choudhury Bazar": 24,
    "Cantonment Road": 22,
    "Balia": 18,
    "Banki": 23,
    "Barabati": 22,
    "Tulasipur": 25,
    "Mangalabag": 24,
    "Link Road": 23,
    "Badambadi": 25,
    "Buxi Bazar": 26,
    "Jagatpur": 28,
    "Dhenkanal": 43,
    "Alipur": 37,
    "Raghunathpur": 33,
    "Banamalipur": 41,
    "Brahmapur": 48,
    "Sabar Sahi": 26,
    "Bhubaneswar": 35,
    "Puri": 58
  },
  "Mahanga": {
    "Banta Sahi": 24,
    "Sarbathipur": 25,
    "Sahid Nagar": 26,
    "Muktapath": 27,
    "Patpur": 4,
    "Duhuria": 19,
    "Bhatapada": 13,
    "Choudwar": 17,
    "Brahman Sahi": 15,
    "Madhupur": 12,
    "Cuttack City": 13,
    "Jobra": 16,
    "Madhupatna": 11,
    "Kanheipur": 10,
    "Sadar Bazar": 13,
    "Daspalla": 23,
    "Puri Gate": 14,
    "Kesharpur": 11,
    "Niali": 12,
    "Bidanasi": 14,
    "Kathajodi": 9,
    "Choudhury Bazar": 14,
    "Cantonment Road": 13,
    "Balia": 12,
    "Banki": 10,
    "Barabati": 13,
    "Tulasipur": 15,
    "Mangalabag": 14,
    "Link Road": 13,
    "Badambadi": 14,
    "Buxi Bazar": 16,
    "Jagatpur": 17,
    "Dhenkanal": 32,
    "Alipur": 27,
    "Raghunathpur": 22,
    "Banamalipur": 30,
    "Brahmapur": 37,
    "Sabar Sahi": 17,
    "Bhubaneswar": 18,
    "Puri": 31
  },
  "Patpur": {
    "Banta Sahi": 22,
    "Sarbathipur": 23,
    "Sahid Nagar": 24,
    "Muktapath": 25,
    "Mahanga": 4,
    "Duhuria": 19,
    "Bhatapada": 14,
    "Choudwar": 18,
    "Brahman Sahi": 16,
    "Madhupur": 13,
    "Cuttack City": 15,
    "Jobra": 18,
    "Madhupatna": 13,
    "Kanheipur": 12,
    "Sadar Bazar": 14,
    "Daspalla": 22,
    "Puri Gate": 15,
    "Kesharpur": 12,
    "Niali": 12,
    "Bidanasi": 14,
    "Kathajodi": 9,
    "Choudhury Bazar": 13,
    "Cantonment Road": 12,
    "Balia": 9,
    "Banki": 7,
    "Barabati": 10,
    "Tulasipur": 12,
    "Mangalabag": 11,
    "Link Road": 10,
    "Badambadi": 13,
    "Buxi Bazar": 14,
    "Jagatpur": 15,
    "Dhenkanal": 28,
    "Alipur": 22,
    "Raghunathpur": 19,
    "Banamalipur": 26,
    "Brahmapur": 33,
    "Sabar Sahi": 14,
    "Bhubaneswar": 16,
    "Puri": 29
  },

  "Badagada": {
    "Dhenkanal": 30,
    "Alipur": 24,
    "Raghunathpur": 20,
    "Banamalipur": 28,
    "Brahmapur": 35,
    "Banta Sahi": 22,
    "Sarbathipur": 21,
    "Sahid Nagar": 19,
    "Muktapath": 22,
    "Mahanga": 21,
    "Patpur": 19,
    "Duhuria": 18,
    "Bhatapada": 15,
    "Choudwar": 17,
    "Brahman Sahi": 13,
    "Madhupur": 15,
    "Cuttack City": 14,
    "Jobra": 18,
    "Madhupatna": 14,
    "Kanheipur": 13,
    "Sadar Bazar": 15,
    "Daspalla": 25,
    "Puri Gate": 20,
    "Kesharpur": 17,
    "Niali": 26,
    "Bidanasi": 22,
    "Kathajodi": 15,
    "Choudhury Bazar": 14,
    "Cantonment Road": 15,
    "Balia": 10,
    "Banki": 12,
    "Barabati": 12,
    "Tulasipur": 16,
    "Mangalabag": 15,
    "Link Road": 13,
    "Badambadi": 14,
    "Buxi Bazar": 17,
    "Jagatpur": 18,
    "Alalabad": 30,
    "Sabar Sahi": 16,
    "Bhubaneswar": 17,
    "Puri": 40
  },
  "Dhenkanal": {
    "Badagada": 30,
    "Alipur": 25,
    "Raghunathpur": 21,
    "Banamalipur": 26,
    "Brahmapur": 33,
    "Banta Sahi": 28,
    "Sarbathipur": 27,
    "Sahid Nagar": 25,
    "Muktapath": 28,
    "Mahanga": 26,
    "Patpur": 24,
    "Duhuria": 22,
    "Bhatapada": 20,
    "Choudwar": 22,
    "Brahman Sahi": 18,
    "Madhupur": 21,
    "Cuttack City": 22,
    "Jobra": 23,
    "Madhupatna": 21,
    "Kanheipur": 18,
    "Sadar Bazar": 19,
    "Daspalla": 30,
    "Puri Gate": 21,
    "Kesharpur": 19,
    "Niali": 28,
    "Bidanasi": 24,
    "Kathajodi": 22,
    "Choudhury Bazar": 21,
    "Cantonment Road": 22,
    "Balia": 16,
    "Banki": 20,
    "Barabati": 18,
    "Tulasipur": 22,
    "Mangalabag": 21,
    "Link Road": 20,
    "Badambadi": 22,
    "Buxi Bazar": 23,
    "Jagatpur": 25,
    "Alalabad": 30,
    "Sabar Sahi": 25,
    "Bhubaneswar": 30,
    "Puri": 45
  },
  "Alipur": {
    "Badagada": 24,
    "Dhenkanal": 25,
    "Raghunathpur": 19,
    "Banamalipur": 23,
    "Brahmapur": 30,
    "Banta Sahi": 22,
    "Sarbathipur": 21,
    "Sahid Nagar": 19,
    "Muktapath": 22,
    "Mahanga": 20,
    "Patpur": 18,
    "Duhuria": 17,
    "Bhatapada": 14,
    "Choudwar": 16,
    "Brahman Sahi": 13,
    "Madhupur": 14,
    "Cuttack City": 14,
    "Jobra": 17,
    "Madhupatna": 13,
    "Kanheipur": 12,
    "Sadar Bazar": 14,
    "Daspalla": 24,
    "Puri Gate": 18,
    "Kesharpur": 16,
    "Niali": 23,
    "Bidanasi": 20,
    "Kathajodi": 15,
    "Choudhury Bazar": 14,
    "Cantonment Road": 15,
    "Balia": 10,
    "Banki": 12,
    "Barabati": 12,
    "Tulasipur": 15,
    "Mangalabag": 14,
    "Link Road": 13,
    "Badambadi": 15,
    "Buxi Bazar": 17,
    "Jagatpur": 19,
    "Alalabad": 24,
    "Sabar Sahi": 15,
    "Bhubaneswar": 25,
    "Puri": 38
  },
  "Raghunathpur": {
    "Badagada": 20,
    "Dhenkanal": 21,
    "Alipur": 19,
    "Banamalipur": 21,
    "Brahmapur": 28,
    "Banta Sahi": 22,
    "Sarbathipur": 21,
    "Sahid Nagar": 19,
    "Muktapath": 21,
    "Mahanga": 22,
    "Patpur": 19,
    "Duhuria": 18,
    "Bhatapada": 17,
    "Choudwar": 17,
    "Brahman Sahi": 15,
    "Madhupur": 17,
    "Cuttack City": 19,
    "Jobra": 21,
    "Madhupatna": 17,
    "Kanheipur": 15,
    "Sadar Bazar": 16,
    "Daspalla": 26,
    "Puri Gate": 18,
    "Kesharpur": 15,
    "Niali": 24,
    "Bidanasi": 21,
    "Kathajodi": 16,
    "Choudhury Bazar": 16,
    "Cantonment Road": 16,
    "Balia": 14,
    "Banki": 16,
    "Barabati": 14,
    "Tulasipur": 18,
    "Mangalabag": 17,
    "Link Road": 16,
    "Badambadi": 16,
    "Buxi Bazar": 18,
    "Jagatpur": 19,
    "Alalabad": 25,
    "Sabar Sahi": 18,
    "Bhubaneswar": 25,
    "Puri": 34
  },
  "Banamalipur": {
    "Badagada": 28,
    "Dhenkanal": 26,
    "Alipur": 23,
    "Raghunathpur": 21,
    "Brahmapur": 30,
    "Banta Sahi": 24,
    "Sarbathipur": 23,
    "Sahid Nagar": 21,
    "Muktapath": 23,
    "Mahanga": 20,
    "Patpur": 18,
    "Duhuria": 17,
    "Bhatapada": 15,
    "Choudwar": 16,
    "Brahman Sahi": 14,
    "Madhupur": 16,
    "Cuttack City": 17,
    "Jobra": 18,
    "Madhupatna": 14,
    "Kanheipur": 13,
    "Sadar Bazar": 15,
    "Daspalla": 25,
    "Puri Gate": 17,
    "Kesharpur": 15,
    "Niali": 21,
    "Bidanasi": 18,
    "Kathajodi": 14,
    "Choudhury Bazar": 15,
    "Cantonment Road": 15,
    "Balia": 12,
    "Banki": 14,
    "Barabati": 12,
    "Tulasipur": 14,
    "Mangalabag": 13,
    "Link Road": 12,
    "Badambadi": 14,
    "Buxi Bazar": 16,
    "Jagatpur": 17,
    "Alalabad": 23,
    "Banamalipur": 0,
    "Sabar Sahi": 17,
    "Bhubaneswar": 25,
    "Puri": 40
  },
  "Brahmapur": {
    "Badagada": 35,
    "Dhenkanal": 33,
    "Alipur": 30,
    "Raghunathpur": 28,
    "Banamalipur": 30,
    "Banta Sahi": 34,
    "Sarbathipur": 33,
    "Sahid Nagar": 31,
    "Muktapath": 33,
    "Mahanga": 32,
    "Patpur": 30,
    "Duhuria": 28,
    "Bhatapada": 25,
    "Choudwar": 27,
    "Brahman Sahi": 24,
    "Madhupur": 27,
    "Cuttack City": 28,
    "Jobra": 29,
    "Madhupatna": 27,
    "Kanheipur": 26,
    "Sadar Bazar": 28,
    "Daspalla": 38,
    "Puri Gate": 30,
    "Kesharpur": 28,
    "Niali": 37,
    "Bidanasi": 34,
    "Kathajodi": 28,
    "Choudhury Bazar": 27,
    "Cantonment Road": 27,
    "Balia": 24,
    "Banki": 26,
    "Barabati": 25,
    "Tulasipur": 28,
    "Mangalabag": 27,
    "Link Road": 26,
    "Badambadi": 28,
    "Buxi Bazar": 30,
    "Jagatpur": 32,
    "Alalabad": 34,
    "Brahmapur": 0,
    "Sabar Sahi": 28,
    "Bhubaneswar": 40,
    "Puri": 60
  },

  "Sabar Sahi": {
    "Bhubaneswar": 9,
    "Puri": 58,
    "Badagada": 12,
    "Dhenkanal": 37,
    "Alipur": 30,
    "Raghunathpur": 29,
    "Banamalipur": 28,
    "Brahmapur": 52,
    "Banta Sahi": 8,
    "Sarbathipur": 7,
    "Sahid Nagar": 6,
    "Muktapath": 8,
    "Mahanga": 12,
    "Patpur": 11,
    "Duhuria": 14,
    "Bhatapada": 10,
    "Choudwar": 15,
    "Brahman Sahi": 6,
    "Madhupur": 13,
    "Cuttack City": 14,
    "Jobra": 16,
    "Madhupatna": 11,
    "Kanheipur": 10,
    "Sadar Bazar": 12,
    "Daspalla": 25,
    "Puri Gate": 19,
    "Kesharpur": 17,
    "Niali": 25,
    "Bidanasi": 16,
    "Kathajodi": 12,
    "Choudhury Bazar": 12,
    "Cantonment Road": 12,
    "Balia": 8,
    "Banki": 13,
    "Barabati": 11,
    "Tulasipur": 15,
    "Mangalabag": 14,
    "Link Road": 14,
    "Badambadi": 14,
    "Buxi Bazar": 16,
    "Jagatpur": 18,
    "Alalabad": 34,
    "Sabar Sahi": 0,
  },
  
 
      
  };
  

  const [startingLocation, setStartingLocation] = useState("");
  const [destination, setDestination] = useState("");
  const [filteredLocations, setFilteredLocations] = useState([]);
  const [price, setPrice] = useState(null);
  const [selectedVehicle, setSelectedVehicle] = useState(null); // Add state for selected vehicle

  // Handle location input change
  const handleLocationChange = (e, setLocation) => {
    const value = e.target.value;
    setLocation(value);

    if (value.length > 0) {
      // Filter locations based on user input only if there's text entered
      setFilteredLocations(
        locations.filter(loc => loc.toLowerCase().includes(value.toLowerCase()))
      );
    } else {
      setFilteredLocations([]);
    }
  };

  // Handle price calculation
  const handlePriceCalculation = () => {
    if (!startingLocation || !destination) {
      alert("Please select both starting and destination locations.");
      return;
    }

    // Fetch the distance between the starting and destination locations
    const distance = distances[startingLocation]?.[destination];

    if (!distance) {
      alert("No distance data available for the selected locations.");
      return;
    }

    // Prices per km
    const vehiclePrices = {
      car: 7 * distance,
      bike: 4 * distance,
      auto: 5 * distance
    };

    setPrice(vehiclePrices);
  };

  // Handle booking redirection
  const handleBooking = () => {
    if (!selectedVehicle) {
      alert("Please select a vehicle to book.");
      return;
    }

    const selectedPrice = price[selectedVehicle];

    if (!selectedPrice) {
      alert("Price not available for the selected vehicle.");
      return;
    }

    // Navigate to the payment page with the selected vehicle type and price
    navigate(`/payment/${selectedVehicle}`, { state: { price: selectedPrice } });
  };

  return (
    <div className="cuttack-page">
      <Navbar />
      <div className="hero-section">
        <div className="hero-left">
          <h2>Enter Your Location and Destination</h2>
          
          <div className="input-group">
            <label>Starting Location</label>
            <input 
              type="text" 
              value={startingLocation} 
              onChange={(e) => handleLocationChange(e, setStartingLocation)} 
              placeholder="Enter your location" 
            />
            {startingLocation && (
              <div className="location-suggestions">
                {filteredLocations.map((loc, index) => (
                  <div 
                    key={index} 
                    className="location-suggestion-item" 
                    onClick={() => {
                      setStartingLocation(loc);
                      setFilteredLocations([]);  
                    }}
                  >
                    {loc}
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="input-group">
            <label>Destination</label>
            <input 
              type="text" 
              value={destination} 
              onChange={(e) => handleLocationChange(e, setDestination)} 
              placeholder="Enter destination" 
            />
            {destination && (
              <div className="location-suggestions">
                {filteredLocations
                  .filter((loc) => loc !== startingLocation)
                  .map((loc, index) => (
                    <div 
                      key={index} 
                      className="location-suggestion-item" 
                      onClick={() => {
                        setDestination(loc);
                        setFilteredLocations([]);  
                      }}
                    >
                      {loc}
                    </div>
                  ))}
              </div>
            )}
          </div>

          <button className="see-price-btn" onClick={handlePriceCalculation}>
            See Price
          </button>

          {price && (
            <div className="price-display">
              <p>Car Price: ₹{price.car}</p>
              <p>Bike Price: ₹{price.bike}</p>
              <p>Auto Price: ₹{price.auto}</p>
            </div>
          )}

          <div className="price-grid">
            <div 
              className={`price-item ${selectedVehicle === 'car' ? 'selected' : ''}`}
              onClick={() => setSelectedVehicle('car')}
            >
              <img src="https://img.icons8.com/ios/50/car--v1.png" alt="Car" className="price-icon" />
              <p>Book Car</p>
              <p>₹{price ? price.car : 0}</p>
            </div>
            <div 
              className={`price-item ${selectedVehicle === 'bike' ? 'selected' : ''}`}
              onClick={() => setSelectedVehicle('bike')}
            >
              <img src="https://img.icons8.com/ios/50/motorcycle.png" alt="Bike" className="price-icon" />
              <p>Book Moto</p>
              <p>₹{price ? price.bike : 0}</p>
            </div>
            <div 
              className={`price-item ${selectedVehicle === 'auto' ? 'selected' : ''}`}
              onClick={() => setSelectedVehicle('auto')}
            >
              <img src="https://img.icons8.com/external-icongeek26-glyph-icongeek26/64/external-autorickshaw-transportation-icongeek26-glyph-icongeek26.png" alt="Auto" className="price-icon" />
              <p>Book Auto</p>
              <p>₹{price ? price.auto : 0}</p>
            </div>
          </div>

          {/* Book Now button */}
          <div className="book-the-bt">
          <button className="book-now-btn" onClick={handleBooking}>
            Book Now
          </button>
          </div>
        </div>

        <div className="hero-right">
          <img src="https://www.holidify.com/images/bgImages/CUTTACK.jpg" alt="Cuttack" className="hero-image" />
        </div>
      </div>
    </div>
  );
};

export default CuttackPage;
